<?php

namespace Creavo\NotifyTaskBundle\Repository;

/**
 * NotificationRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
