<?php

namespace Creavo\NotifyTaskBundle\Repository;

/**
 * TaskRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
